name: fluent_query_generator
description: Fluent Query Generator
version: 0.0.1
repository: https://github.com/gocal/fluent_query

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  collection: ^1.14.0
  recase: ">=2.0.1 <4.0.0"
  meta: ^1.1.0
  path: ^1.6.0
  json_annotation: ^3.0.0
  stream_transform: ">=0.0.20 <2.0.0"

  # CLI
  args: ^1.5.0
  logging: ">=0.11.0 <1.0.0"
  cli_util: ^0.1.0

  # Fluent Query
  fluent_query:

  # Dart analysis
  analyzer: ^0.40.0
  analyzer_plugin_fork: ^0.3.0
  source_span: ^1.5.5

  # Build system
  build: ^1.1.0
  build_resolvers: ^1.3.3
  build_config: ">=0.3.1 <1.0.0"
  dart_style: ^1.3.3
  source_gen: ^0.9.4

dev_dependencies:
  test: ^1.6.0
  build_runner: ^1.6.7
  build_test: ^0.10.10
  json_serializable: ^3.0.0

executables:
  fluent_query_generator:

dependency_overrides:
  fluent_query:
    path: ../fluent_query
