name: fluent_query
description: Fluent Query
version: 0.0.1
repository: https://github.com/gocal/fluent_query

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  convert: ^2.1.1
  collection: ^1.0.0
  synchronized: ^2.1.0
  pedantic: ^1.0.0

dev_dependencies:
  build_runner: "^1.10.1"
  test: ^1.9.0
  mockito: ^4.1.0
